name: Update Languages Overview

on:
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite UTC
  workflow_dispatch:      # Permite execução manual via interface do GitHub

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script to update README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
        run: python generate_languages.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Atualiza lista de linguagens automaticamente" || echo "Sem alterações"
          git push
